#ifndef SENSORS_CONFIG_H
#define SENSORS_CONFIG_H

#define AMBIENT_LIGHT_SENSOR_IMPLEMENTATION OPT4003DNPRQ1
#define MOTION_SENSOR_IMPLEMENTATION        LIS2DW12TR
#define DISTANCE_SENSOR_IMPLEMENTATION      VL53L3CX

#endif // SENSORS_CONFIG_H