#ifndef SENSORS_CONFIG_H
#define SENSORS_CONFIG_H

#define AMBIENT_LIGHT_SENSOR_IMPLEMENTATION OPT4003DNPRQ1
#define MOTION_SENSOR_IMPLEMENTATION        LIS2DW12TR
#define DISTANCE_SENSOR_IMPLEMENTATION      VL53L3CX

// Threshold values for sensors
#define MOTION_THRESHOLD_G          0.5f
#define LIGHT_LOW_THRESHOLD_LUX     18
#define LIGHT_HIGH_THRESHOLD_LUX    20
#define DISTANCE_THRESHOLD_CM       1
#define DISTANCE_READING_TIMEOUT_MS 5000    // 5 seconds in milliseconds

#endif // SENSORS_CONFIG_H